#--------------------------------------------------------------------
# path to build directory (generated by cmake)
#--------------------------------------------------------------------
PRE_TARGETDEPS += $$PWD/../../setup.pri
include($$PWD/../../setup.pri)


#--------------------------------------------------------------------
# project
#--------------------------------------------------------------------
QT -= core gui
TARGET = sample-minimal
TEMPLATE = app
CONFIG += c++11
CONFIG -= qt

DESTDIR = $$OUTPUT_DIR/bin
QMAKE_CLEAN += $$DESTDIR/$$TARGET

CONFIG(debug, debug|release):
    DEFINES += _DEBUG
DEFINES += GP_USE_GAMEPAD

INCLUDEPATH += $$OUTPUT_DIR/include/gplayengine/
INCLUDEPATH += $$OUTPUT_DIR/include/gplayengine/thirdparty

#--------------------------------------------------------------------
# platform specific
#--------------------------------------------------------------------
linux: {
    DEFINES += __linux__
    PRE_TARGETDEPS += $$OUTPUT_DIR/lib/libgplay-deps.a
    PRE_TARGETDEPS += $$OUTPUT_DIR/lib/libgplay.a
    LIBS += -L$$OUTPUT_DIR/lib/ -lgplay
    LIBS += -L$$OUTPUT_DIR/lib/ -lgplay-deps
    LIBS += -lm -lGL -lrt -ldl -lX11 -lpthread -lsndio
    QMAKE_POST_LINK += $$quote(rsync -rau $$PWD/game.config $${DESTDIR}/$${TARGET}.config$$escape_expand(\n\t))
}

#--------------------------------------------------------------------
# files
#--------------------------------------------------------------------
SOURCES += \
    src/minimal.cpp

HEADERS += \
    src/minimal.hpp

